# Generated by Django 4.1.7 on 2023-02-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_category', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='/img')),
                ('item_added', models.IntegerField()),
            ],
        ),
    ]
